// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskDelegationAPI.Models;

public partial class Task
{
    public int TaskID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public string Priority { get; set; }

    public int? GivenTo { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime Deadline { get; set; }

    public DateTime? DateComplete { get; set; }

    public bool Recurring { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual User GivenToNavigation { get; set; }
}