// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskDelegationAPI.Models;

public partial class User
{
    public int UserID { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int NumberOfTasks { get; set; }

    public int TasksComplete { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Task> TaskCreatedByNavigations { get; set; } = new List<Task>();

    public virtual ICollection<Task> TaskGivenToNavigations { get; set; } = new List<Task>();

    public virtual ICollection<UserPermission> UserPermissions { get; set; } = new List<UserPermission>();
}